### ISSUE TITLE
get_owl.sh is missing

### ISSUE THREAD

**Issue by rodja** [zauberzeug/lizard#35]
As pointed out by @BenGeissler in https://github.com/zauberzeug/field_friend/issues/28#issuecomment-2059388035, there is no `get_owl.sh` file in the latest `main` branch of [lizard](https://github.com/zauberzeug/lizard). But it is needed for installing Lizard as stated in the documentation: https://lizard.dev/tools/#development. He found the file in the commit history of the main branch and cloned [owl](https://lizard.dev/tools/#development) by hand.

**Comment by falkoschindler** [comment]
The file get_owl.sh has been removed more than two years ago in https://github.com/zauberzeug/lizard/commit/bc3dfbd82cffaf47dd120c39669d0129e185de2f. It isn't needed anymore, because owl has been included as a submodule. So I think we can simply remove its reference from the documentation:
https://github.com/zauberzeug/lizard/blob/00662315436f375aae9e25153418c22f83d8d761/docs/tools.md?plain=1#L58-L62
There is already an instruction about installing submodules:
https://github.com/zauberzeug/lizard/blob/00662315436f375aae9e25153418c22f83d8d761/docs/tools.md?plain=1#L66-L70
